version: "3.8"

services:
  browser:
    build: .
    command: [ "python3", "/home/app/main.py" ]
    environment:
      - DISPLAY=192.168.1.225:0.0
    volumes:
      - ./main.py:/home/app/main.py
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M
